config/routes.rb
Hitchik::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show] do
    member do
      post :rate
    end
  end

  resources :hitchikes do
    resources :reservations, only: [:create, :destroy, :new]
    get :my, :on => :collection
    get :search, :on => :collection
    get :wtf, :on => :collection
    member do
      post :rate
    end
  end

  resources :hitchike_requests

  match '/terms',   to: 'static_pages#terms'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'

  root :to => 'static_pages#home'

end

app/models/hitchike.rb
# == Schema Information
#
# Table name: hitchikes
#
#  id             :integer          not null, primary key
#  source         :string(255)
#  destination    :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  departure      :datetime
#  seats          :integer
#  notes          :text
#  gmaps          :boolean
#  latitude       :float
#  longitude      :float
#  rating_average :decimal(6, 2)    default(0.0)
#  price          :decimal(8, 2)
#  luggage        :string(255)
#

class Hitchike < ActiveRecord::Base
  attr_accessible :destination, :gmaps, :latitude, :longitude, :source, :departure, :seats, :notes, :rating_average, :price, :luggage
  #Rating
  ajaxful_rateable :stars=> 5, :dimensions => [:avaliacaogeral], :allow_update => true, :cache_colum => :rating_average
  #Maps
  acts_as_gmappable

  def free_seats
    return seats - reservations.length()
  end

  def is_old
    DateTime::now > departure
  end

  def gmaps4rails_address
    destination
  end


  belongs_to :user
  has_many :reservations
end

app/controllers/hitchikes_controller.rb
class HitchikesController < ApplicationController

    before_filter :authenticate_user!, :except => [:index, :show, :search]

    # GET /hitchikes/search
    # TODO: partida e data
    def search
        @hitchikes = Hitchike.select { |h| ! h.is_old }
  
        # filtra partida
        unless params[:p].blank?
            @hitchikes = @hitchikes.select { |h| h.source.casecmp(params[:p].strip) == 0 }
        end
        
        # filtra destino
        
        @circles = { }
        unless params[:q].blank?
            begin
                loc = Gmaps4rails.geocode(params[:q]).first
            rescue
                redirect_to root_path
                return
            end
            raio = params[:d].to_f
            @hitchikes = @hitchikes.select do |h|
                dist = Geocoder::Calculations.distance_between([loc[:lat], loc[:lng]], [h.latitude, h.longitude], :units=>:km)
                dist <= raio
            end
            lat = loc[:lat]
            lng = loc[:lng]
            rad = raio*1000
            @circles = {"circles"    => { "data" => "[ {\"lng\": #{lng}, \"lat\": #{lat}, \"radius\": #{rad}} ]" }}
        end
        
        if params[:ord] == 'd'
            @hitchikes.sort_by!(&:departure)
        end

        @json = @hitchikes.to_gmaps4rails
        @markers = @json

        
        # meter o centro do circulo
        #if params[:q] and params[:q].size > 0
        #    @markers += ".concat( [ {\"lat\": #{lat}, \"lng\": #{lng}} ] )"
        #end

        # filtra data
        unless params[:dt].blank?
            search_date = Date.parse(params[:dt])
            DateTime.now.to_date
            @hitchikes = @hitchikes.select { |h| h.departure.to_date == search_date }
        end

        if @hitchikes.blank?
            @noresults = true
            @hitchike_request = HitchikeRequest.new(:source => params[:p],
                :destination => params[:q], :departure => params[:dt])
            render 'hitchike_requests/new'
            return
        end

        respond_to do |format|
            format.html { render :index }
            format.json { render json: @hitchikes}
        end
    end

    # GET /hitchikes/my
    def my
        @hitchikes = current_user.hitchikes.all      
    end

    # GET /hitchikes
    def index
        @hitchikes = Hitchike.all
        @json = @hitchikes.to_gmaps4rails
        @markers = @json
        @circles = { }

        respond_to do |format|
            format.html { render :index }
            format.json { render json: @hitchikes}
        end

    end

    # GET /hitchikes/1 Implemetado o Maps
    def show
        @hitchike = Hitchike.find( params[:id] )
        @json = @hitchike.to_gmaps4rails

        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @hitchike}
        end
    end

    # GET /hitchikes/new
    def new
        @hitchike = current_user.hitchikes.new( :departure => DateTime.now.to_s(:short) )
    end

    #  POST /hitchikes/
    def create
        @hitchike = current_user.hitchikes.new( params[:hitchike] )
        if @hitchike.save
            redirect_to @hitchike
        else
            render 'static_pages/home'
        end
    end
    
    #Ranking
    def rate
        @hitchike = Hitchike.find(params[:id])
        @hitchike.rate(params[:stars], current_user, params[:dimension])

    end

    # GET wtf
    def wtf
        @hide = true
        render :noresults
    end
end

app/helpers/hitchikes_helper.rb
module HitchikesHelper
end

app/views/hitchikes/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "hitchike_index" %>
  <%= ajaxful_rating_style %>
<% end %>

<% content_for :buttons do %>
    <li class="lbt"><%= button_to 'Home', root_path, method: "get" %></li>
<% end %>

<div id="barra"> 

    <div id="sort">
    <%= form_tag(search_hitchikes_path, :method=> "get") do %>
    <div id="sorttext">
        <p> <%= label_tag(:ord, "Ordenar por:") %>
            <%= select_tag(:ord, options_for_select( [['Data', 'd'], ['Preço', 'p']] )) %>
        </p>
        <p> <%= submit_tag("Ordenar") %> </p>
    <% end %>
    <%= form_tag(new_hitchike_request_path, :method => :get) do %>
        <%= hidden_field_tag 'p', params["p"] %>
        <%= hidden_field_tag 'q', params["q"] %>
        <%= hidden_field_tag 'dt', params["dt"] %>
        <br/> <p> <%= submit_tag "Pedir Boleia" %> </p>
    <% end %>
    </div>
    </div>

    <div id="cage">
        
        <% @hitchikes.each do |hitchike| %>
        
        <%= link_to hitchike do %>
        <a href="javascript:void(0)" onclick="showRoute('<%= hitchike.source %>', '<%= hitchike.destination %>');">
        <div class="results"> 
            <div class="info">
                <img class="foto" src="<%= hitchike.user.profile_image %>" </img>
                <p> <%= hitchike.user.name %> </p>  
                <p> <%= ratings_for hitchike.user, :static, :small => true, :dimension => :avaliacaogeral %> </p>
            </div>
            
            <div class="texto">
                <p> De <%= hitchike.source %> para <%= hitchike.destination %> </p>
                <p> Data: <%= hitchike.departure.to_s(:short) %> </p>
                <p> Lugares livres: <%= hitchike.free_seats %> / <%= hitchike.seats %> </p>
                <p> Preço: <%= number_to_currency(hitchike.price , :unit => "€") %> </p>
                <p> Bagagem: <%= hitchike.luggage %> </p>
                <p> Observações: <%= hitchike.notes %></p>
                <p> <%= button_to "Ver detalhes", hitchike, :method=>"get" %> </p>
            </div>

        </div> 
        <% end %>
        </a>

        <% end %>

    </div>

</div>


<script type="text/javascript">

function showRoute(origin, destination) {
    Gmaps.map.initialize();
    Gmaps.map.direction_conf.origin = origin;
    Gmaps.map.direction_conf.destination = destination;
    Gmaps.map.create_direction();
    //showCircle();
};



// nao e preciso por agora
function showCircle() {
<% if not @circles.empty? %>
    Gmaps.map.circles = <%=raw @circles["circles"]["data"] %>;
    Gmaps.map.create_circles();
<% end %>
};


 
 </script>

<!--%= gmaps({
       "direction"   => { "data" => { "from" => Hitchike.first.source, "to" => Hitchike.first.destination } }
            })
 %-->

<%= gmaps( {"markers" => {"data" => @markers}}.merge( @circles ) )
%>

<!-- %= gmaps4rails(@json) % -->


<!-- https://github.com/apneadiving/Google-Maps-for-Rails/wiki/%28Multiple%29-Maps -->

app/views/hitchikes/my.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "hitchike_my" %>
  <%= ajaxful_rating_style %>
<% end %>

<div class="container">

        <a href="/"><img id="logo" src="/assets/logo_carro2.png" class="logo"/></a>

        <div id="esq"> 
          <img class="foto" src="<%= current_user.profile_image %>" </img>
          <p> <%= current_user.name %> </p>
        </div>

        <div id="dir"> <h1> As minhas boleias </h1>
            
          <% @hitchikes.each do |hitchike| %>
            <%= link_to(hitchike) do %>
              <div class="resultado">
                  <p id="editar"> <input type="button" value="Editar" /> </p>
                  <p> <b> Partida: </b> <%= hitchike.source %> </p>
                  <p> <b> Destino: </b> <%= hitchike.destination %> </p>
                  <p> <b> Data: </b> <%= hitchike.departure.to_s(:short) %> </p>
                  <p> <b> Lugares totais: </b> <%= hitchike.seats %> </p>
                  <p> <b> Lugares livres: </b> <%= hitchike.free_seats %> </p>
                  <p> <b> Preço: </b> <%= number_to_currency(hitchike.price , :unit => "€") %> </p>
                  <p> <b> Bagagem: </b> <%= hitchike.luggage %> </p>
                  <p> <b> Observações </b> <%= hitchike.notes %> </p>
              </div>
            <% end %>
          <% end %>

          <!--p id="antigas">
          <button class="btn" type="button"> Boleias Antigas</button>
          </p>

          <p id="Conc">
          <button class="btn" type="button"> Concorrência</button>
          </p-->

        </div>
        <%= render "layouts/footer" %>


</div>



app/views/hitchikes/new.html.erb
<h1> Nova boleia </h1>

<%= form_for(@hitchike) do |f| %>

<p>
    <%= f.label :source %>
    <%= f.text_field :source %>
</p>
<p>
    <%= f.label :destination %>
    <%= f.text_field :destination %>
</p>
<p>
    <%= f.label :departure %>
    <%= f.text_field :departure %>
</p>
<p>
    <%= f.label :seats %>
    <%= f.number_field :seats %>
</p>
<p>
    <%= f.label :notes %>
    <%= f.text_area :notes %>
</p>


<%= f.submit %>
<% end %>

app/views/hitchikes/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "hitchike_show" %>
<% end %>

<div class="container">

  <a href="/"><img class="logo" src="/assets/logo_carro2.png" /></a>
  <div id="reserva">
  


  </div>


     <div id="esq">

          <div class="results"> 

            <div class="texto">
              <p> <b> Partida: </b> <%= @hitchike.source %> </p>
              <p> <b> Destino: </b> <%= @hitchike.destination %> </p>
              <p> <b> Data: </b> <%= @hitchike.departure.to_s(:short) %> </p>
              <p> <b> Lugares livres: </b> <%= @hitchike.free_seats %> / <%= @hitchike.seats %> </p>
              <p> <b> Preço: </b> <%= number_to_currency(@hitchike.price , :unit => "€") %> </p>
              <p> <b> Bagagem: </b> <%= @hitchike.luggage %> </p>
              <p> <b> Observações: </b> <%= @hitchike.notes %> </p>
            </div>
            <div class="info condutor">
              <a href="<%= @hitchike.user.fb_page %>" target="_blank">
                <p> Condutor </p> <!-- pode nao ser o condutor -->
                <img class="foto" src="<%= @hitchike.user.profile_image %>" </img>
                <p> <%= @hitchike.user.name %> </p>
              </a>
              <p> <%= ratings_for @hitchike.user, :static, :small => true, :dimension => :avaliacaogeral %> </p>
            </div>
       <% unless current_user.nil? %>
    <% if @hitchike.is_old %>
      <%= button_to "Já foi", "#", :disabled => "disabled", :id => "reservar" %>
    <% elsif @hitchike.user == current_user %>
      <%= button_to "Editar boleia", @hitchike, :method => "get", :id => "reservar"%>
    <% elsif current_user.reserved_hitchike? @hitchike %>
      <%= button_to "Anular reserva", [@hitchike, current_user.find_reservation(@hitchike)], :method => "delete", :id => "reservar" %>
    <% elsif @hitchike.free_seats <= 0 %>
      <%= button_to "Sem lugares", "#", :disabled => "disabled", :id => "reservar" %>
    <% else %>
      <%= form_for [@hitchike, Reservation.new(:hitchike_id => @hitchike.id)] do |f| %>
        <%= f.submit "Reservar lugar", :id => "reservar" %>
      <% end %>
    <% end %>
  <% end %>


          </div>
     
          <div id="fotos"> <h3>Passageiros</h3>
              <% @hitchike.reservations.each do |reservation| %>
                <div class="info">
                  <a href="<%= reservation.user.fb_page %>" target="_blank">
                    <img class="foto" src="<%= reservation.user.profile_image %>" </img>
                    <p> <%= reservation.user.name %> </p>
                  </a>
                </div>
              <% end %>
          </div>
          <div id="butoes">
            <%= button_to_function "Voltar", "history.back()", :id => "voltar" %>
          </div>
     </div>

     <div id="dir">

          <%= gmaps({
       "direction"   => { "data" => { "from" => @hitchike.source, "to" => @hitchike.destination } }
            })
 %>
          <!--div id="chat"> <h3> Deixe aqui a sua mensagem</h3></div-->

     </div>

     <%= render "layouts/footer" %>
</div>
