config/routes.rb
Hitchik::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show] do
    member do
      post :rate
    end
  end

  resources :hitchikes do
    resources :reservations, only: [:create, :destroy, :new]
    get :my, :on => :collection
    get :search, :on => :collection
    get :wtf, :on => :collection
    member do
      post :rate
    end
  end

  resources :hitchike_requests

  match '/terms',   to: 'static_pages#terms'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<div id="footer" class="try" align="center">

  <center>
    <%= link_to "Home", root_path , :class => "rodape" %>
    <%= link_to "Termos de utilização", terms_path, :class => "rodape"%>
    <%= link_to "Sobre nós", about_path, :class => "rodape"%>
    <%= link_to "Contactos", contact_path, :class => "rodape"%>
    <a class="rodape" id="made">Made in Coimbra</a>
  </center>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Share It!</title>

  <%= javascript_include_tag :defaults %>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <link href='https://fonts.googleapis.com/css?family=Questrial' rel = "stylesheet" type="text/css" ></link>

</head>
<body>

<nav>
<ul>
    <% if signed_in? %>
    <%= yield :buttons %>
    <li><%= button_to 'Logout', destroy_user_session_path, method: "delete" %></li>
    <li><%= button_to "As minhas boleias", my_hitchikes_path, method: "get" %></li>
    <% else %>
    <!--li><%= link_to 'Login', new_user_session_path %></li-->
    <li>
      <%= link_to omniauth_authorize_path(:user, :facebook) do %>
        <img src="/assets/connect_light_medium_long.gif" />
      <% end %>
    </li>
    <% end %>
</ul>
</nav>


<%= yield %>
<%= yield :scripts %>

</body>
</html>